### ISSUE TITLE
xAxis and yAxis attributes not having effect on chart. 

### ISSUE THREAD

**Issue by kpl39** [avdaredevil/highcharts-chart#21]
I am trying to use multiple yAxes for my chart. Usually in high charts I would use an array with multiple yAxis objects inside. In your docs it looks like that attribute is not meant for arrays. 

I have my chart set up like this: 

`      <highcharts-chart  type="spline" data='{{chartData.series}}' title='Test'  xAxis='{{chartData.xAxis}}' yAxis='{{chartData.yAxis}}'></highcharts-chart>`

And my chartData object: 

`chartData = {
  series: [{}], 
  xAxis: {title: {text: "X Axis"} },
 yAxis: [
  {title: {text: "Y Axis 1"} },
  {title: {text: "Y Axis 2"},
   opposite: true 
}
  ]
}
`
I do not see an xAxis or yAxis title. 

I tried using the same code on the demo of your webcomponents page (here's a [screenshot](https://s3.amazonaws.com/incentiveapi/deals/highCharts.png)), but it didn't seem to work there either. 

Can you tell me if I'm doing something wrong or if this is a bug? 

Great job on the web component by the way! 

Thanks!

**Comment by avdaredevil** [comment]
Hey @kpl39, so this is by design. Most use cases normally revolve around 1 `x` and 1 `y` axis. Therefore there are convenience keys available to easily modify the chart with `x-label`, `x-zoom`, etc.

## Bug:
You were almost there with the `xAxis` property, but the polymer rules are that camel-case properties on HTML must be transposed to dash-case for property binding:
> So `xAxis` needs to be modified like `<highcharts-chart x-axis="[[someConfig]]" ...>`

## Option 1:
If you do want extended support for `x` and `y` axises, you could extend off of this component and define the `xAxis` observer to work similar to the `data` key observer, which supports single/multi series options.

## Option 2:
Another option, which I've used historically for my own projects, is to create a _wrapper component_, that takes your raw data, and splits the binding between **_keys_** and the **_imperative functions_** provided with the library to achieve the functionality you're looking for, with optional support for performance enhancement via _debouncing_ quick updates. 

As usual for any custom function like adding a new axis, feel free to access the `myChart._chart` object, which is the Highcharts object. And you can use the traditional Highchart API on it!

## Option 3:
Though not recommended due to performance implications, you could also just feed your entire `chartData` object as input to the `highchartOptions`  key. (ex. `<highcharts-chart highchart-options="[[chartData]]">`).

**Comment by kpl39** [comment]
Thank you for the explanation. I'll try to set up the xAxis observer to work like the data key observer.

**Comment by avdaredevil** [comment]
No problem mate! If you liked the library please make sure to leave a star to show your support!
