### ISSUE TITLE
How to use height-responsive?

### ISSUE THREAD

**Issue by lycandroid** [avdaredevil/highcharts-chart#23]
Hi, thanks for providing this component.  Saved me a lot of time.

Is the height-responsive attribute supposed to mean to expand the chart to its container?  If so I can't seem to get it to work.

I tried:
```
<div style="height:1000px">
   <highcharts-chart height-responsive data="[1,2,3]"></highcharts-chart>
</div>
```
And so I would expect to see a chart of height 1000px but I'm not.

Have I misunderstood what this attribute is for?

Many thanks.

**Comment by avdaredevil** [comment]
Yeah `hight-responsive` lets you reflow the chart height wise as well. I've included an example [in this fiddle](https://jsfiddle.net/82hLx5p3/1/).

Basic premise is that `hight-responsive` makes the element have no inherent height, so you could either give height to the `<highcharts-chart>` element or its parent (by setting `<highcharts-chart>`'s height to `100%`).

But that will not reflow the chart for you! Since changing an elements height **_does not_** trigger an event, thus you still need to manually run the `resizeChart()` function on the component as soon as it's parent is loaded and **_visible_**.

**Comment by lycandroid** [comment]
Thanks, yes I can see that working so my problem must be something else I'm doing wrong which I can't figure out at the moment.   I'm wrapping your <highcharts-chart> in my own (polymer 2.x) component so I'm no doubt doing something wrong there.

In the meantime I added Polymer.IronResizableBehavior to my component and handle the iron-resize with:
```
    _onResize(e) {
      var chart = this.$.chart;
      var renderer = this.$.chart.renderer;

      if ( renderer.width != this.offsetWidth || renderer.height != this.offsetHeight )
        chart._chart.setSize(this.offsetWidth, this.offsetHeight, false );
    }
```

I suppose possibly you could add iron-resize support to <highcharts-chart> then it would auto adjust height without requiring the manual call to resizeChart()?

**Comment by avdaredevil** [comment]
Sure that sounds like a splendid idea! I would however remark that your resize implementation may not be very performance friendly. The difference between `reflow()` and `setSize()` is very noticeable. I'd recommend the former.

**Comment by avdaredevil** [comment]
@lycandroid A polymer 2.0 version of this lib is now completed if you'd like to use that instead. It's under the branch `polymer-2.0`!

Branch: [***`polymer-2.0`***](https://github.com/avdaredevil/highcharts-chart/tree/polymer-2.0)
PR: #24
